const Payment=require('../../models/shopping-models/payment-model');const {AppError}=require('../../utils/app-error');
function range(query){const today=new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Tehran'});const end=query.to||today,defaultStart=new Date(Date.now()-29*864e5).toLocaleDateString('en-CA',{timeZone:'Asia/Tehran'}),start=query.from||defaultStart;if(!/^\d{4}-\d{2}-\d{2}$/.test(start)||!/^\d{4}-\d{2}-\d{2}$/.test(end))throw new AppError(400,'بازه تاریخ معتبر نیست.');const from=new Date(start+'T00:00:00+03:30'),to=new Date(+new Date(end+'T00:00:00+03:30')+864e5);if(!Number.isFinite(+from)||!Number.isFinite(+to)||to<=from||to-from>366*864e5)throw new AppError(400,'بازه باید بین یک روز و یک سال باشد.');return {from,to,start,end};}
const sum=field=>({$sum:field});
async function report(query){const dates=range(query),match={status:{$in:['paid','refunded']},verifiedAt:{$gte:dates.from,$lt:dates.to}};
const base=[{$match:match},{$sort:{verifiedAt:1}},{$group:{_id:'$order',paidAt:{$first:'$verifiedAt'}}},{$lookup:{from:'orders',localField:'_id',foreignField:'_id',as:'order'}},{$unwind:'$order'},{$lookup:{from:'users',localField:'order.user',foreignField:'_id',as:'customer'}},{$set:{gender:{$ifNull:[{$arrayElemAt:['$customer.gender',0]},'unknown']}}}];
const filters={};if(query.province)filters['order.shippingAddressSnapshot.province']=String(query.province).slice(0,100);if(['male','female','unknown'].includes(query.gender))filters.gender=query.gender;if(Object.keys(filters).length)base.push({$match:filters});
const itemMatch={};if(query.product)itemMatch['order.items.productSnapshot.name']={$regex:require('../../utils/search-pattern')(String(query.product).slice(0,80)),$options:'i'};if(query.size)itemMatch['order.items.productSnapshot.size']=String(query.size).slice(0,30);if(query.color)itemMatch['order.items.productSnapshot.color']=String(query.color).slice(0,60);
const paid=[{$match:{'order.paymentStatus':'paid'}}],items=[...paid,{$unwind:'$order.items'},...(Object.keys(itemMatch).length?[{$match:itemMatch}]:[])];
const result=await Payment.aggregate([...base,{$facet:{
 totals:[...paid,{$group:{_id:null,orders:sum(1),sales:sum('$order.subtotal'),shipping:sum('$order.shippingAmount'),collected:sum('$order.totalAmount'),pairs:sum('$order.totalPairs'),customers:{$addToSet:'$order.user'}}}],
 refunds:[{$match:{'order.paymentStatus':'refunded'}},{$group:{_id:null,orders:sum(1),amount:sum('$order.totalAmount')}}],
 timeline:[...paid,{$group:{_id:{$dateToString:{date:'$paidAt',format:'%Y-%m-%d',timezone:'Asia/Tehran'}},sales:sum('$order.subtotal'),orders:sum(1)}},{$sort:{_id:1}}],
 provinces:[...paid,{$group:{_id:{$ifNull:['$order.shippingAddressSnapshot.province','نامشخص']},sales:sum('$order.subtotal'),orders:sum(1)}},{$sort:{sales:-1}}],
 genders:[...paid,{$group:{_id:'$gender',sales:sum('$order.subtotal'),orders:sum(1)}}],
 statuses:[...paid,{$group:{_id:'$order.status',orders:sum(1)}}],
 customers:[...paid,{$group:{_id:'$order.user',name:{$first:{$concat:[{$ifNull:[{$arrayElemAt:['$customer.firstname',0]},'']},' ',{$ifNull:[{$arrayElemAt:['$customer.lastname',0]},'']}] }},orders:sum(1),sales:sum('$order.subtotal')}},{$sort:{sales:-1}}],
 products:[...items,{$match:{'order.items.itemType':'Product'}},{$group:{_id:{id:'$order.items.item',size:'$order.items.productSnapshot.size',color:'$order.items.productSnapshot.color'},name:{$first:'$order.items.productSnapshot.name'},quantity:sum('$order.items.quantity'),sales:sum('$order.items.totalPrice'),discount:sum({$subtract:[{$multiply:[{$ifNull:['$order.items.originalUnitPrice','$order.items.unitPrice']},'$order.items.quantity']},'$order.items.totalPrice']})}},{$sort:{quantity:-1}}],
 boxes:[...items,{$match:{'order.items.itemType':'Box'}},{$group:{_id:'$order.items.item',name:{$first:'$order.items.productSnapshot.name'},quantity:sum('$order.items.quantity'),sales:sum('$order.items.totalPrice'),discount:sum({$subtract:[{$multiply:[{$ifNull:['$order.items.originalUnitPrice','$order.items.unitPrice']},'$order.items.quantity']},'$order.items.totalPrice']})}},{$sort:{quantity:-1}}],
 components:[...paid,{$unwind:'$order.items'},{$match:{'order.items.itemType':'Box'}},{$unwind:'$order.items.components'},{$group:{_id:{id:'$order.items.components.product',size:'$order.items.components.size',color:'$order.items.components.color'},name:{$first:'$order.items.components.name'},quantity:sum({$multiply:['$order.items.quantity','$order.items.components.quantity']})}},{$sort:{quantity:-1}}]
}}]).allowDiskUse(true).option({maxTimeMS:30000});const r=result[0];r.totals=r.totals[0]||{orders:0,sales:0,shipping:0,collected:0,pairs:0,customers:[]};r.totals.customers=r.totals.customers.length;r.totals.average=r.totals.orders?Math.round(r.totals.sales/r.totals.orders):0;r.refunds=r.refunds[0]||{orders:0,amount:0};
const combined=new Map();for(const [rows,field] of [[r.products,'single'],[r.components,'boxed']])for(const row of rows){const key=JSON.stringify(row._id);const entry=combined.get(key)||{...row,single:0,boxed:0};entry[field]+=row.quantity;combined.set(key,entry);}r.combined=[...combined.values()].map(x=>({...x,total:x.single+x.boxed})).sort((a,b)=>b.total-a.total);
if(query.product||query.size||query.color)r.combined=r.combined.filter(x=>(!query.product||x.name?.includes(query.product))&&(!query.size||x._id.size===query.size)&&(!query.color||x._id.color===query.color));
if(query.summaryOnly){r.period={from:dates.start,to:dates.end};return r;}const ids=r.customers.map(c=>c._id);const firstPayments=ids.length?await Payment.aggregate([{$match:{user:{$in:ids},status:{$in:['paid','refunded']},verifiedAt:{$ne:null}}},{$group:{_id:'$user',first:{$min:'$verifiedAt'}}}]):[];const firstMap=new Map(firstPayments.map(x=>[String(x._id),x.first]));r.customers=r.customers.map(c=>({...c,isNew:firstMap.get(String(c._id))>=dates.from}));r.totals.newCustomers=r.customers.filter(c=>c.isNew).length;r.totals.returningCustomers=r.customers.length-r.totals.newCustomers;
const products=await require('../../models/product-models/product-model').find({isActive:true}).select('name variants stock').lean();const sales=new Map();for(const x of r.combined){const key=String(x._id.id)+'|'+(x._id.size||'')+'|'+(x._id.color||'');sales.set(key,x.total);}r.inventory=[];for(const p of products){for(const v of p.variants?.length?p.variants:[{size:'free-size',color:'',stock:p.stock,isActive:true}]){if(v.isActive===false)continue;const sold=sales.get(String(p._id)+'|'+v.size+'|'+(v.color||''))||0;if(v.stock<=5||sold===0)r.inventory.push({name:p.name,size:v.size,color:v.color,stock:v.stock,sold,reason:v.stock<=5?'موجودی کم':'بدون فروش در بازه'});}}r.inventory.sort((a,b)=>a.stock-b.stock);
r.totals.discount=r.products.reduce((n,x)=>n+x.discount,0)+r.boxes.reduce((n,x)=>n+x.discount,0);r.totals.singleSales=r.products.reduce((n,x)=>n+x.sales,0);r.totals.boxSales=r.boxes.reduce((n,x)=>n+x.sales,0);
if(query.detail){const normalize=s=>String(s||'').replace(/[۰-۹]/g,c=>String(c.charCodeAt(0)-1776)).replace(/ي/g,'ی').replace(/ك/g,'ک').toLowerCase(),term=normalize(query.detail).slice(0,100);for(const key of ['products','boxes','components','combined'])r[key]=r[key].filter(x=>normalize([x.name,x._id?.size,x._id?.color].join(' ')).includes(term));}
r.period={from:dates.start,to:dates.end};r.generatedAt=new Date();return r;}
module.exports={report,range};