const fs = require('node:fs');
const path = require('node:path');
const request = (name, method, route, body, captures = {}, description = '') => {
  const item = { name, request: { method, header: body ? [{ key:'Content-Type', value:'application/json' }] : [], url:'{{baseUrl}}'+route, description, ...(body ? { body:{mode:'raw',raw:JSON.stringify(body,null,2),options:{raw:{language:'json'}}} } : {}) } };
  item.event=[{listen:'test',script:{type:'text/javascript',exec:["pm.test('Request succeeded', () => pm.expect(pm.response.code).to.be.within(200, 299));",...Object.entries(captures).map(([variable,expr])=>`if(pm.response.code < 300) { const data = pm.response.json().data; const value = ${expr}; if(value !== undefined) pm.collectionVariables.set('${variable}', String(value)); }`)]}}];
  return item;
};
const upload=(name,route,field='images',method='POST')=>({name,request:{method,url:'{{baseUrl}}'+route,description:'Choose a local image file. Max 5MB each; max 10 gallery images.',body:{mode:'formdata',formdata:[{key:field,type:'file',src:[]}]}}});
const folder=(name,item)=>({name,item});
const address={title:'خانه',recipientName:'مشتری پاور',recipientPhone:'{{phone}}',province:'تهران',city:'تهران',addressLine:'نشانی آزمایشی؛ قبل از ارسال اصلاح شود',postalCode:'1234567890',buildingNumber:'۱',unit:'۱',isDefault:true};
const collection={info:{name:'PAWEAR V2 — Backend + Admin + SSR',description:'Three synchronized phases. Enable the Postman cookie jar. Set private credentials locally, never share/export them. Log in as admin before catalog writes, then as customer before checkout. Successful creates capture IDs automatically. Requests that delete/deactivate or complete mock payments are manual, not an unattended production runner.',schema:'https://schema.getpostman.com/json/collection/v2.1.0/collection.json'},variable:Object.entries({baseUrl:'http://127.0.0.1:3000/api',siteUrl:'http://127.0.0.1:3000',phone:'',password:'',adminPhone:'09000000000',adminPassword:'',newPassword:'',otp:'',categoryId:'',subCategoryId:'',brandId:'',variantId:'',shippingMethod:'post',productId:'',productSlug:'',boxId:'',boxSlug:'',itemId:'',addressId:'',orderId:'',paymentId:'',userId:'',imagePath:'',refundReference:'',trackingCode:''}).map(([key,value])=>({key,value,type:'string'})),item:[
 folder('01 — Authentication & account',[
 request('Admin password login','POST','/auth/login',{phonenumber:'{{adminPhone}}',password:'{{adminPassword}}'}),
 request('Register customer','POST','/auth/register',{firstname:'مشتری',lastname:'پاور',phonenumber:'{{phone}}',password:'{{password}}'},{userId:'data.user._id'}),
 request('Customer password login','POST','/auth/login',{phonenumber:'{{phone}}',password:'{{password}}'},{userId:'data.user._id'}),
 request('Request OTP','POST','/auth/otp/request',{phonenumber:'{{phone}}'}, {}, 'No SMS provider yet; development prints code in server terminal. Set otp locally. 60 second cooldown.'),
 request('Verify OTP / create customer','POST','/auth/otp/verify',{phonenumber:'{{phone}}',code:'{{otp}}',firstname:'مشتری',lastname:'پاور'},{userId:'data.user._id'}),
 request('Set password after recent OTP','PUT','/auth/password',{password:'{{newPassword}}'}),
 request('Customer confirms package received','POST','/orders/{{orderId}}/received',{}),
 request('My account','GET','/account'),request('Edit profile','PATCH','/account',{firstname:'مشتری',lastname:'پاور'}),request('Logout all sessions','POST','/auth/logout')]),
 folder('02 — Public catalog',[
 request('Categories','GET','/categories'),request('Subcategories','GET','/subCategories'),request('Products','GET','/products?limit=24&page=1'),request('Product by id','GET','/products/id/{{productId}}'),request('Product by slug','GET','/products/slug/{{productSlug}}'),request('Boxes','GET','/boxes'),request('Box by id','GET','/boxes/id/{{boxId}}'),request('Box by slug','GET','/boxes/slug/{{boxSlug}}')]),
 folder('03 — Admin catalog & media',[
 request('Create category','POST','/categories',{name:'جوراب',isActive:true,sortOrder:0},{categoryId:'data.category._id'}),
 request('Create subcategory','POST','/subCategories',{name:'روزمره',category:'{{categoryId}}',isActive:true},{subCategoryId:'data.subCategory._id'}),
 request('Create brand','POST','/brands',{name:'پاور',isActive:true},{brandId:'data.brand._id'}),
 request('Create free size option','POST','/admin/catalog-options/sizes',{label:'FREE-SIZE'}),
 request('Create colour option','POST','/admin/catalog-options/colors',{name:'سفید',code:'#ffffff'}),
 request('Create free-size sock','POST','/products',{name:'جوراب روزمره پاور',category:'{{categoryId}}',subCategory:'{{subCategoryId}}',brandId:'{{brandId}}',variants:[{size:'FREE-SIZE',color:'سفید',price:120000,stock:40}],gender:'unisex',description:'توضیح واقعی جوراب',details:[{title:'جنس',value:'ترکیب واقعی الیاف'}],isActive:true,isFeatured:true},{productId:'data.product._id',productSlug:'data.product.slug',variantId:'data.product.variants[0]._id'}),
 request('Edit sock','PATCH','/products/{{productId}}',{variants:[{_id:'{{variantId}}',size:'FREE-SIZE',color:'سفید',price:125000,stock:40}],description:'توضیحات به‌روز محصول'}),
 request('Create fixed two-pair box','POST','/boxes',{name:'باکس دو جفتی پاور',products:[{product:'{{productId}}',quantity:2}],discount:10,isActive:true},{boxId:'data.box._id',boxSlug:'data.box.slug'}),
 request('Edit box','PATCH','/boxes/{{boxId}}',{discount:5}),
 ...['products','boxes','categories','subCategories'].map(k=>request('Admin list '+k,'GET','/'+k+'/all')),
 request('Admin product','GET','/products/admin/{{productId}}'),request('Admin box','GET','/boxes/admin/{{boxId}}'),
 upload('Upload sock gallery','/products/{{productId}}/gallery'),request('Select sock cover / retain images','PUT','/products/{{productId}}/gallery',{images:['{{imagePath}}'],coverImage:'{{imagePath}}'}),
 upload('Upload box gallery','/boxes/{{boxId}}/images'),request('Select box cover / retain images','PUT','/boxes/{{boxId}}/images',{images:['{{imagePath}}'],coverImage:'{{imagePath}}'}),
 upload('Category icon','/categories/edit-icon/{{categoryId}}','icon','PATCH'),upload('Subcategory icon','/subCategories/edit-icon/{{subCategoryId}}','icon','PATCH'),
 request('Deactivate sock (manual)','DELETE','/products/{{productId}}'),request('Deactivate box (manual)','DELETE','/boxes/{{boxId}}')]),
 folder('04 — Customer cart, wishlist & address',[
 request('My cart','GET','/cart'),request('Add sock','POST','/cart',{itemType:'Product',item:'{{productId}}',variantId:'{{variantId}}',quantity:1},{itemId:'data.cart.items.find(i => String(i.item) === pm.collectionVariables.get("productId"))._id'}),request('Add box','POST','/cart',{itemType:'Box',item:'{{boxId}}',quantity:1},{itemId:'data.cart.items.find(i => String(i.item) === pm.collectionVariables.get("boxId"))._id'}),request('Set row quantity','PATCH','/cart/{{itemId}}',{quantity:2}),request('Remove row (manual)','DELETE','/cart/{{itemId}}'),request('Wishlist','GET','/wishlists'),request('Add favorite','POST','/wishlists',{productId:'{{productId}}'}),request('Remove favorite','DELETE','/wishlists/{{productId}}'),request('My addresses','GET','/addresses'),request('Create shipping address','POST','/addresses',address,{addressId:'data.address._id'}),request('Edit address','PATCH','/addresses/{{addressId}}',{title:'خانه اصلی'}),request('Set default address','PATCH','/addresses/{{addressId}}/default',{}),request('Delete address (manual)','DELETE','/addresses/{{addressId}}')]),
 folder('05 — Checkout & payment',[
 request('Preview current prices (no order created)','POST','/checkout',{}),request('Prepare order with address','POST','/orders',{addressId:'{{addressId}}',shippingMethod:'{{shippingMethod}}'},{orderId:'data.order._id'}),request('Start payment & reserve stock','POST','/payments/order/{{orderId}}',{}, {paymentId:'data.payment._id'}, 'Open data.redirectUrl for a live gateway. For local mock use the next request. Cart clears when reservation succeeds.'),request('Mock success — local only','POST','/payments/mock/{{paymentId}}/success',{}),request('My order','GET','/orders/{{orderId}}'),request('Order history','GET','/orders/history'),request('All my orders','GET','/orders'),request('My payment','GET','/payments/{{paymentId}}'),request('My payments','GET','/payments'),request('Cancel unpaid prepared order (manual)','DELETE','/orders/{{orderId}}')]),
 folder('08 — V2 shipping and sizes',[
 request('Read shipping fees','GET','/admin/settings/shipping'),request('Set shipping fees (Toman)','PUT','/admin/settings/shipping',{methods:[{key:'post',name:'پست',sockAmount:45000,boxAmount:70000,isActive:true,sortOrder:1},{key:'tipax',name:'تیپاکس',sockAmount:60000,boxAmount:90000,isActive:true,sortOrder:2}]},{},'One fee per order. Mixed carts use the maximum. Paid orders keep the original fee.'),request('Add first size option','POST','/admin/catalog-options/sizes',{label:'40-43'}),request('Add second size option','POST','/admin/catalog-options/sizes',{label:'43-46'}),request('Create sized sock','POST','/products',{name:'جوراب سایزبندی پاور',category:'{{categoryId}}',subCategory:'{{subCategoryId}}',brandId:'{{brandId}}',variants:[{size:'40-43',color:'سفید',price:100000,stock:10,isActive:true},{size:'43-46',color:'سفید',price:120000,stock:8,isActive:true}]},{productId:'data.product._id',productSlug:'data.product.slug',variantId:'data.product.variants[0]._id'}),request('Add selected size','POST','/cart',{itemType:'Product',item:'{{productId}}',size:'40-43',quantity:1}),request('Create fixed box with sizes','POST','/boxes',{name:'باکس سایزبندی',products:[{product:'{{productId}}',size:'40-43',quantity:1},{product:'{{productId}}',size:'43-46',quantity:1}]},{boxId:'data.box._id'}),request('Mark packed','PATCH','/orders/admin/{{orderId}}',{status:'packed',packingNote:'بسته آماده ارسال است'}),request('Ship with carrier','PATCH','/orders/admin/{{orderId}}',{status:'shipped',carrier:'پست',trackingCode:'{{trackingCode}}'})]),
 folder('06 — Admin operations',[
 request('Dashboard','GET','/admin/dashboard'),request('All orders','GET','/orders/all'),request('Order detail','GET','/orders/admin/{{orderId}}'),request('Mark shipped','PATCH','/orders/admin/{{orderId}}',{status:'shipped',trackingCode:'{{trackingCode}}'}),request('Mark delivered','PATCH','/orders/admin/{{orderId}}',{status:'delivered'}),request('All payments','GET','/payments/all'),request('Review queue','GET','/payments/all?requiresReview=true&reviewStatus=pending'),request('Payments for order','GET','/payments/admin/order/{{orderId}}'),request('Resolve: stock supplied','PATCH','/payments/admin/{{paymentId}}/review',{resolution:'stock_supplied'}),request('Record externally completed refund','PATCH','/payments/admin/{{paymentId}}/review',{resolution:'refunded',refundReference:'{{refundReference}}'}, {}, 'Does NOT transfer money. Records a refund already performed externally. Resolution is final.'),request('All carts','GET','/cart/all'),request('Users','GET','/users'),request('User addresses','GET','/addresses/admin/user/{{userId}}'),request('Suspend customer','PATCH','/users/{{userId}}',{accountStatus:{status:'suspended',reason:'admin_deactivated'}}),request('Reactivate customer','PATCH','/users/{{userId}}',{accountStatus:{status:'active',reason:null}})]),
 folder('07 — SSR pages & technical SEO', ['/', '/shop', '/boxes','/product/{{productSlug}}','/box/{{boxSlug}}','/admin','/admin/products','/admin/boxes','/cart','/checkout','/account','/sitemap.xml','/robots.txt','/health'].map(route=>({name:'GET '+route,request:{method:'GET',url:'{{siteUrl}}'+route,description:'HTML uses the same cookie session as the API; admin requires admin login.'}})))
]};
fs.writeFileSync(path.join(__dirname,'../docs/PAWEAR.postman_collection.json'),JSON.stringify(collection,null,2)+'\n');
console.log('Postman updated: '+collection.item.reduce((n,f)=>n+f.item.length,0)+' requests.');
